name: CI

on: [push]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: serializing workflow runs
        uses: softprops/turnstyle@v1
        with:
          same-branch-only: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: download heroku cli
        uses: wei/curl@master
        with:
          args: https://cli-assets.heroku.com/install.sh >>./.github/heroku_install.sh
      - name: Install heroku cli
        run: |
              sudo chmod u+x ./.github/heroku_install.sh
              ls -al ./.github/
              ./.github/heroku_install.sh
        shell: bash
      - name: Restart Heroku
        run: heroku ps:restart --app ct-payment-integration-java
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      - name: Build with Gradle
        run: ./gradlew --info build
        env:
          CT_PROJECT_KEY:  project-payment-21
          CT_CLIENT_ID: ${{ secrets.CT_CLIENT_ID }}
          CT_CLIENT_SECRET: ${{ secrets.CT_CLIENT_SECRET }}
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          CT_PAYONE_INTEGRATION_URL: https://ct-payment-integration-java.herokuapp.com/PAYMENT/commercetools/handle/payments/
